name: Flujo proba
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Fumo la mota verde."
      - run: echo "ğŸ§ En Pol Aymerich olora a sardina!"
      - run: echo "ğŸ” En Biel fa 3 mesos que no es dutxa."
